export const iconMapping = {
    academics: '/assets/academics.svg',
    donationsDark: '/assets/donations-dark.svg',
    donationsLight: '/assets/donations-light.svg',
    logout: '/assets/logout.svg',
    profile: '/assets/profile.svg',
    myDegreeLight: '/assets/my-degree-light.svg',
    myDegreeDark: '/assets/my-degree-dark.svg',
    examsDark: '/assets/exams-dark.svg',
    examsLight: '/assets/exams-light.svg',
    collapse: '/assets/collapse.svg',
    degreeProgress: '/assets/degree-progress.svg',
    play: '/assets/play.svg',
    creditOverview: '/assets/credit-overview.svg',
    examStats: '/assets/exam-stats.svg',
    dropdownArrow: '/assets/dropdown-arrow.svg',
    grow: '/assets/grow.svg',
    arrowRight: '/assets/arrow-right.svg',
    calendar: '/assets/calendar.svg',
    calendarDark: '/assets/calendar-dark.svg',
    star: '/assets/star.svg',
    starOutline: '/assets/star-outline.svg',
    speedoMeter: '/assets/speedometer.svg',
    user: '/assets/user.svg',
    hamburger: '/assets/hamburger.svg',
};